param_int: 1
param_float: 1.
param_str: hi
param_list_of_everything: [a, 1, '1']
param_dict:
  k0: v0
  k1: v1
  nested_k:
    k00: v00
    and_so_on: more_values
batch_size: 20
inner_batch_size: 20
best_model_name: best_twitter_trained_model_emotions.pth #best_twitter_trained_model.pth
model_name: twitter_trained_model_emotions.pth
mean_vec_emb_file: twitter_mean_class_embedding.p
median_vec_emb_file: twitter_median_class_embedding.p
experiment_name: cur_time

data_file: twitter/preprocessed_data.csv
csv_file_name_train: 'twitter_train.csv'
csv_file_name_test: 'twitter_test.csv'
visual_csv_file_name_train: 'visual_twitter_train.csv'
visual_csv_file_name_test: 'visual_twitter_test.csv'

#data_file: cleaned_twitter_data_BillGates_KendallJenner.csv
#csv_file_name_train: twitter_train_BillGates_KendallJenner.csv
#csv_file_name_test: twitter_test_BillGates_KendallJenner.csv
#visual_csv_file_name_train: visual_twitter_train_BillGates_KendallJenner.csv
#visual_csv_file_name_test: visual_twitter_test_BillGates_KendallJenner.csv

tgt_file_pairs_list: twitter_pairs_list_BillGates_KendallJenner.p
num_workers: 10
plot_only_clustering: False
desired_labels: all
undesired_label: ''
data_name: Twitter
resume: False # resume running in wb
run_id: ''
load_model: False