param_int: 1
param_float: 1.
param_str: hi
param_list_of_everything: [a, 1, '1']
param_dict:
  k0: v0
  k1: v1
  nested_k:
    k00: v00
    and_so_on: more_values
batch_size: 400
inner_batch_size: 10
best_model_name: best_28_classes_trained_model_emotions.pth
model_name: 28_classes_trained_model_emotions.pth
mean_vec_emb_file: emotions_mean_class_embedding.p
median_vec_emb_file: emotions_median_class_embedding.p
data_file: ['goemotions_1.csv', 'goemotions_2.csv', 'goemotions_3.csv'] #https://github.com/google-research/google-research/tree/master/goemotions
experiment_name: cur_time
csv_file_name_train: 'emotions_train.csv'
csv_file_name_test: 'emotions_test.csv'
visual_csv_file_name_train: 'visual_emotions_train.csv'
visual_csv_file_name_test: 'visual_emotions_test.csv'
tgt_file_pairs_list: emotions_pairs_list.p
num_workers: 10
plot_only_clustering: False
desired_labels: 'all' #[embarrassment, joy, anger, love, annoyance, nervousness]
undesired_label: 'neutral'
resume: True # resume running in wb
load_model: True
