#senticap
dataset: senticap # senticap,flickrstyle10k
style_type: roberta  #'style_embed' or 'emoji' or 'erc' or 'roberta' #todo
data_split: test #val, test #todo
#dataset: senticap # senticap,flickrstyle10k
model: stylized_zero_cap_experiments # stylized_zero_cap_experiments, capdec

#metrics: [bleu1, bleu3, bleu4, rouge, CLIPScoreRef, CLIPScore, style_classification, fluency, style_classification_emoji]   # ['bleu','rouge','meteor', 'spice', 'CLIPScoreRef','CLIPScore','style_classification', 'fluency']
#metrics: [CLIPScore, style_classification, fluency]   # ['bleu','rouge','meteor', 'spice', 'CLIPScoreRef','CLIPScore','style_classification', 'fluency']
#todo
#metrics: [CLIPScore, fluency]   # ['bleu','rouge','meteor', 'spice', 'CLIPScoreRef','CLIPScore','style_classification', 'fluency']
#metrics: [CLIPScore, style_classification_roberta, fluency]   # ['bleu','rouge','meteor', 'spice', 'CLIPScoreRef','CLIPScore','style_classification', 'fluency']
#metrics: [CLIPScore, style_classification, fluency]   # ['bleu','rouge','meteor', 'spice', 'CLIPScoreRef','CLIPScore','style_classification', 'fluency']
metrics: [CLIPScore, style_classification_roberta, fluency]   # ['bleu','rouge','meteor', 'spice', 'CLIPScoreRef','CLIPScore','style_classification', 'fluency']

update_ViT: False

#metrics: [style_classification_emoji]   # ['bleu','rouge','meteor', 'spice', 'CLIPScoreRef','CLIPScore','style_classification', 'fluency']
styles:
  senticap: [positive, negative]  #[positive, negative, factual] #todo
  flickrstyle10k: [humor, romantic]

desired_labels:
  senticap: [positive, negative] #[factual, positive, negative]
  flickrstyle10k: [humor, romantic] #[factual, humor, romantic]
res_path2eval:
  senticap:
#    zerostylecap_emoji:  /home/nlp/tzufar/experiments/stylized_zero_cap_experiments/senticap_ZeroStyleCap_with_emoji/19_03_2023/tmp/total_results_zerstylecap_emoji_batch.csv
#    ZeroStyleCap_f_36:  /home/nlp/tzufar/experiments/stylized_zero_cap_experiments/senticap_ZeroStyleCap_f_036/total_results_text_style_f_36.csv
#    ZeroStyleCap_real_std: /home/nlp/tzufar/experiments/stylized_zero_cap_experiments/senticap_ZeroStyleCap_real_std/total_results_ZeroStyleCap_real_std.csv
#    capdec_positive: ~/experiments/capdec/res_positive.csv
#    capdec_negative: ~/experiments/capdec/res_negative.csv
#    prompt_manipulation: /home/nlp/tzufar/experiments/stylized_zero_cap_experiments/senticap_fixed_param_25_3_23/prompt_manipulation/d4jnwh7t-copper-cherry-13/results_23_36_32__25_03_2023.csv
#    image_manipulation: /home/nlp/tzufar/experiments/stylized_zero_cap_experiments/senticap_fixed_param_25_3_23/image_manipulation/h9yfdeh2-misunderstood-forest-12/results_23_33_40__25_03_2023.csv
#    image_and_prompt_manipulation: /home/nlp/tzufar/experiments/stylized_zero_cap_experiments/senticap_fixed_param_25_3_23/image_and_prompt_manipulation/jk7xzo7u-dulcet-bush-11/results_23_29_58__25_03_2023.csv
#    ZeroStyleCap: /home/nlp/tzufar/experiments/stylized_zero_cap_experiments/senticap_fixed_param_25_3_23/ZeroStyleCap/xuk6u1fz-eternal-night-7/results_21_29_00__23_03_2023.csv
#    #erc
#    ZeroStyleCap: /home/bdaniela/experiments/stylized_zero_cap_experiments/erc_weighted_loss/28_04_2023/total_results_erc.csv
#    ZeroStyleCap: /home/bdaniela/results/zero_style_cap/erc_old_params/total_results_erc.csv
#     #roberta val
#    ZeroStyleCap: /Users/danielabendavid/experiments/stylized_zero_cap_experiments/senticap_StylizedZeroCap_roBERTa/val_set/03_05_2023/total_results_zero_style_cap_roBerta_val.csv
#     ZeroStyleCap: /Users/danielabendavid/experiments/stylized_zero_cap_experiments/senticap_StylizedZeroCap_roBERTa/val_set/03_05_2023/total_results_text_style_.csv
#     ZeroStyleCap: /home/bdaniela/experiments/stylized_zero_cap_experiments/senticap_StylizedZeroCap_roBERTa_val_set/03_05_2023/total_results_text_style_.csv
#     ZeroStyleCap: /Users/danielabendavid/experiments/stylized_zero_cap_experiments/senticap_StylizedZeroCap_roBERTa_val_set_weighted_loss/05_05_2023/total_results_text_style_.csv
#     #style embed - 14.5.23
#     ZeroStyleCap: /Users/danielabendavid/experiments/zero_style_cap/senticap/style_embed/senticap_StylizedZeroCap_my_embedding_model_real_std/total_results_text_style_.csv

#     ZeroStyleCap: /Users/danielabendavid/experiments/zero_style_cap/senticap/style_embed/senticap_StylizedZeroCap_my_embedding_model_8/total_results_text_style_.csv
#     ZeroStyleCap: /Users/danielabendavid/experiments/zero_style_cap/senticap/erc/senticap_StylizedZeroCap_erc/total_results_text_style_.csv
#     stop in good res -15.5.23
#     ZeroStyleCap: /Users/danielabendavid/experiments/zero_style_cap/senticap/style_embed/senticap_StylizedZeroCap_stop_in_good_res/15_05_2023/total_results_text_style_.csv
#     ZeroStyleCap: /Users/danielabendavid/experiments/zero_style_cap/senticap/source_zero_stylecap/29_05_2023/total_results.csv
    #baseline - 31.5.23
    prompt_manipulation: /Users/danielabendavid/experiments/zero_style_cap/senticap/baseline/prompt_manipulation/total_results_prompt_manipulation_.csv
    image_manipulation: /Users/danielabendavid/experiments/zero_style_cap/senticap/baseline/image_manipulation/total_results_image_manipulation.csv
    image_and_prompt_manipulation: /Users/danielabendavid/experiments/zero_style_cap/senticap/baseline/image_and_prompt_manipulation/total_results_image_and_prompt_manipulation.csv


#    ZeroStyleCap: /Users/danielabendavid/experiments/zero_style_cap/senticap/baseline/prompt_manipulation/total_results_prompt_manipulation_.csv
#     ZeroStyleCap: /Users/danielabendavid/experiments/zero_style_cap/senticap/baseline/image_manipulation/total_results_image_manipulation.csv
#     ZeroStyleCap: /Users/danielabendavid/experiments/zero_style_cap/senticap/baseline/image_and_prompt_manipulation/total_results_image_and_prompt_manipulation.csv
#      style embed
#     ZeroStyleCap: /Users/danielabendavid/experiments/zero_style_cap/senticap/style_embed/senticap_StylizedZeroCap_my_embedding_model_real_std/total_results_text_style_.csv
#     ZeroStyleCap: /Users/danielabendavid/experiments/zero_style_cap/senticap/style_embed/senticap_StylizedZeroCap_my_embedding_model_8/total_results_text_style_style_embed_8.csv
     #finetuned roberta best sweep
#     ZeroStyleCap: /Users/danielabendavid/experiments/zero_style_cap/senticap/roberta/finetuned_roberta_best_sweep/total_results_text_style_finetuned_roberta.csv
#    val on 20 imgs - prompt_manipulation
#     ZeroStyleCap: /Users/danielabendavid/experiments/zero_style_cap/senticap/baseline/val_20_imgs/senticap_StylizedZeroCap_prompt_manipulation/09_06_2023/1-63sniirz-autumn-cherry-1/results_10_34_42__09_06_2023.csv
    #val on 20 imgs - image_manipulation
#     ZeroStyleCap: /Users/danielabendavid/experiments/zero_style_cap/senticap/baseline/val_20_imgs/senticap_StylizedZeroCap_image_manipulation/09_06_2023/1-5vs2g62a-blooming-salad-1/results_10_34_48__09_06_2023.csv
    #val on 20 imgs - prompt_and_image_manipulation
#     ZeroStyleCap: /Users/danielabendavid/experiments/zero_style_cap/senticap/baseline/val_20_imgs/senticap_StylizedZeroCap_prompt_and_image_manipulation/09_06_2023/1-ma9am9qf-summer-durian-1/results_10_34_51__09_06_2023.csv
    #val on 20 imgs - capdec
#     ZeroStyleCap: /Users/danielabendavid/experiments/zero_style_cap/senticap/baseline/val_20_imgs/capdec/res_val_20_capdec_senticap.csv
#    val on 20 imgs - prompt_manipulation
#     ZeroStyleCap: /home/nlp/tzufar/experiments/zero_style_cap/senticap/style_embed/senticap_StylizedZeroCap_prompt_manipulation/11_06_2023/6-lynfqmpx-radiant-dawn-6/results_12_34_47__11_06_2023.csv
#     ZeroStyleCap: /Users/danielabendavid/experiments/zero_style_cap/senticap/baseline/val_20_imgs/senticap_StylizedZeroCap_prompt_manipulation/11_06_2023/6-lynfqmpx-radiant-dawn-6/results_12_33_12__11_06_2023.csv
    #val on 20 imgs - image_manipulation
#     ZeroStyleCap: /home/nlp/tzufar/experiments/zero_style_cap/senticap/style_embed/senticap_StylizedZeroCap_image_manipulation/11_06_2023/10-y0bf9ym5-trim-star-10/results_12_33_12__11_06_2023.csv
#     ZeroStyleCap: /Users/danielabendavid/experiments/zero_style_cap/senticap/baseline/val_20_imgs/senticap_StylizedZeroCap_image_manipulation/11_06_2023/10-y0bf9ym5-trim-star-10/results_12_33_12__11_06_2023.csv
    #val on 20 imgs - prompt_and_image_manipulation
#     ZeroStyleCap: home/nlp/tzufar/experiments/zero_style_cap/senticap/style_embed/senticap_StylizedZeroCap_prompt_and_image_manipulation/11_06_2023/6-pcsfvx05-pretty-paper-6/results_12_34_47__11_06_2023.csv
#     ZeroStyleCap: /Users/danielabendavid/experiments/zero_style_cap/senticap/baseline/val_20_imgs/senticap_StylizedZeroCap_prompt_and_image_manipulation/11_06_2023/6-pcsfvx05-pretty-paper-6/results_12_33_19__11_06_2023.csv
#     val 20 vpos20
#     ZeroStyleCap: /Users/danielabendavid/experiments/zero_style_cap/senticap/roberta/StylizedZeroCap_roberta_3_loss_v20pos/11_06_2023/18-hponm3ll-feasible-sweep-18/results_05_55_02__11_06_2023.csv
#     val 20vneg22
#     ZeroStyleCap: /Users/danielabendavid/experiments/zero_style_cap/senticap/roberta/StylizedZeroCap_roberta_3_loss_v22neg/11_06_2023/9-i5ujidxz-crisp-sweep-9/results_11_48_42__11_06_2023.csv
#     v_test_neg_wo update CLIP
#     ZeroStyleCap: /Users/danielabendavid/experiments/zero_style_cap/senticap/roberta/StylizedZeroCap_roberta_3_loss_v_test_neg/total_results_text_style_v_test_neg_wo_update_clip.csv
##     v_test_pos_wo update CLIP
#     ZeroStyleCap: /Users/danielabendavid/experiments/zero_style_cap/senticap/roberta/StylizedZeroCap_roberta_3_loss_v_test_pos/total_results_text_style_v_test_pos_wo_update_clip.csv


#
  flickrstyle10k:
#    capdec_humor: ~/experiments/capdec/27_2_23/res_humor.csv
#    capdec_romantic: ~/experiments/capdec/27_2_23/res_romantic.csv
#    prompt_manipulation: /home/nlp/tzufar/experiments/stylized_zero_cap_experiments/5_3_23/c1p9kpt8-smoldering-heart-7/results_13_07_48__15_02_2023.csv
#    image_manipulation: /home/nlp/tzufar/experiments/stylized_zero_cap_experiments/5_3_23/v584fr44-desiring-etchings-11/results_13_39_19__15_02_2023.csv
#    image_and_prompt_manipulation: /home/nlp/tzufar/experiments/stylized_zero_cap_experiments/5_3_23/gkdoticx-loyal-sweetheart-9/results_13_30_05__15_02_2023.csv
#    ZeroStyleCap: /home/nlp/tzufar/experiments/stylized_zero_cap_experiments/15_02_2023/6mcw38e7-eager-dove-19/results_22_10_24__15_02_2023.csv
    prompt_manipulation: /home/nlp/tzufar/experiments/stylized_zero_cap_experiments/flickrstyle10k_fixed_param_25_3_23/prompt_manipulation/total_results_prompt_manipulation.csv
    image_manipulation: /home/nlp/tzufar/experiments/stylized_zero_cap_experiments/flickrstyle10k_fixed_param_25_3_23/image_manipulation/total_results_image_manipulation.csv
    image_and_prompt_manipulation: /home/nlp/tzufar/experiments/stylized_zero_cap_experiments/flickrstyle10k_fixed_param_25_3_23/image_and_prompt_manipulation/total_results_image_and_prompt_manipulation.csv
    ZeroStyleCap: /home/nlp/tzufar/experiments/stylized_zero_cap_experiments/flickrstyle10k_fixed_param_25_3_23/ZeroStyleCap/total_results_text_style_Flickrstyle10k.csv


# finetuned roBERTa
finetuned_roberta_model_path: ~/checkpoints/finetuned_roberta/pytorch_model.bin
finetuned_roberta_config: ~/checkpoints/finetuned_roberta/config.json
labels_dict_idxs_roberta:
  senticap:
#    positive: 1
    positive: 2
    negative: 0
  flickrstyle10k:
    humor: 0
    romantic: 1

max_num_imgs2test:
  senticap: -1
  flickrstyle10k: 1000


tgt_eval_results_file_name: avg_evaluation.csv
tgt_eval_results_file_name_for_all_frames: evaluation_all_frames.csv


tgt_eval_results_path: ~/experiments/stylized_zero_cap_experiments/27_2_23/avg_evaluation.csv
tgt_eval_results_path_for_all_frames: ~/experiments/stylized_zero_cap_experiments/27_2_23/evaluation_all_frames.csv
dir_path_for_eval_only_fluency: ~/experiments/stylized_zero_cap_experiments/27_2_23/fluency_statistics

factual_captions_path:
  senticap: /Users/danielabendavid/data/source/coco/factual_captions.pkl

annotations_path:
  senticap: /Users/danielabendavid/data/senticap/annotations
  flickrstyle10k: /Users/danielabendavid/data/flickrstyle10k/annotations

imgs_path:
  senticap: /Users/danielabendavid/data/senticap/images
  flickrstyle10k: /Users/danielabendavid/data/flickrstyle10k/images
txt_cls_model_paths:
  senticap: ~/checkpoints/best_models/senticap/best_senticap_text_style_classification_model.pth
  flickrstyle10k: ~/checkpoints/best_models/flickrstyle10k/best_flickrstyle10k_text_style_classification_model.pth
hidden_state_to_take_txt_cls:
  senticap: -1
  flickrstyle10k: -1

txt_embed_model_paths:
  senticap: ~/checkpoints/best_models/senticap/best_text_style_embedding_model_senticap.pth
  flickrstyle10k: ~/checkpoints/best_models/flickrstyle10k/best_text_style_embedding_model_flickrstyle10k.pth

hidden_state_to_take_txt_style_embedding:
  senticap: -2

model_based_on: 'bert'
test_imgs:
  senticap: /home/nlp/tzufar/data/senticap/images/test
  flickrstyle10k: /home/nlp/tzufar/data/flickrstyle10k/images/test


#specific_imgs_to_test: [225571, 471814, 72873, 357322, 106314, 368459, 575135, 423830, 51258, 265596, 551518, 448703]
#specific_img_idxs_to_test: [60, 61, 62, 63, 64, 65, 66, 67, 128, 129, 130, 131, 132, 133, 134, 135]
img_idx_to_start_from: 0
max_num_of_imgs: 5 #-1
specific_idxs_to_skip: [2,3]


labels_dict_idxs:
  senticap:
    positive: 0
    negative: 1
  flickrstyle10k:
    humor: 0
    romantic: 1

#emoji
use_single_emoji_style: False
idx_emoji_style_dict:
  senticap:
#    positive: 53
#    negative: 34
    positive: [0,4,6,7,8,13,15,16,17,18,23,24,36,40,53,60] # 53
    negative: [1,2,3,5,12,22,27,29,32,34,35,37,39,42,43,44,45,46,52,55,56,58] # 34
  flickrstyle10k:
    humor: #0
    romantic: #23

emoji_vocab_path: ~/projects/torchMoji/model/vocabulary.json
emoji_pretrained_path: ~/projects/torchMoji/model/pytorch_model.bin
maxlen_emoji_sentence: 30
num_classes: 64
#idx_emoji_style_dict:
#  senticap:
#    positive: 53
#    negative: 34
#  flickrstyle10k:
#    humor: 0
#    romantic: 23
