#senticap
dataset: senticap # senticap,flickrstyle10k
style_type: 'emoji' #'style_embed' or 'emoji'
data_split: test #val, test
#dataset: senticap # senticap,flickrstyle10k
model: stylized_zero_cap_experiments # stylized_zero_cap_experiments, capdec
metrics: [bleu1, bleu3, bleu4, rouge, CLIPScoreRef, CLIPScore, style_classification, fluency, style_classification_emoji]   # ['bleu','rouge','meteor', 'spice', 'CLIPScoreRef','CLIPScore','style_classification', 'fluency']
#metrics: [fluency]   # ['bleu','rouge','meteor', 'spice', 'CLIPScoreRef','CLIPScore','style_classification', 'fluency']
#metrics: [bleu1, bleu3, bleu4]   # ['bleu','rouge','meteor', 'spice', 'CLIPScoreRef','CLIPScore','style_classification', 'fluency']
#metrics: [CLIPScoreRef, CLIPScore]   # ['bleu','rouge','meteor', 'spice', 'CLIPScoreRef','CLIPScore','style_classification', 'fluency']
desired_labels:
  senticap: [positive, negative] #[factual, positive, negative]
  flickrstyle10k: [humor, romantic] #[factual, humor, romantic]
res_path2eval:
  senticap:
    zerostylecap_emoji:  /home/nlp/tzufar/experiments/stylized_zero_cap_experiments/senticap_ZeroStyleCap_with_emoji/19_03_2023/tmp/total_results_zerstylecap_emoji_batch.csv
#    ZeroStyleCap_f_36:  /home/nlp/tzufar/experiments/stylized_zero_cap_experiments/senticap_ZeroStyleCap_f_036/total_results_text_style_f_36.csv
#    ZeroStyleCap_real_std: /home/nlp/tzufar/experiments/stylized_zero_cap_experiments/senticap_ZeroStyleCap_real_std/total_results_ZeroStyleCap_real_std.csv
#    capdec_positive: ~/experiments/capdec/27_2_23/res_positive.csv
#    capdec_negative: ~/experiments/capdec/27_2_23/res_negative.csv
  flickrstyle10k:
    capdec_humor: ~/experiments/capdec/27_2_23/res_humor.csv
    capdec_romantic: ~/experiments/capdec/27_2_23/res_romantic.csv
    prompt_manipulation: /home/nlp/tzufar/experiments/stylized_zero_cap_experiments/5_3_23/c1p9kpt8-smoldering-heart-7/results_13_07_48__15_02_2023.csv
    image_manipulation: /home/nlp/tzufar/experiments/stylized_zero_cap_experiments/5_3_23/v584fr44-desiring-etchings-11/results_13_39_19__15_02_2023.csv
    image_and_prompt_manipulation: /home/nlp/tzufar/experiments/stylized_zero_cap_experiments/5_3_23/gkdoticx-loyal-sweetheart-9/results_13_30_05__15_02_2023.csv
    ZeroStyleCap: /home/nlp/tzufar/experiments/stylized_zero_cap_experiments/15_02_2023/6mcw38e7-eager-dove-19/results_22_10_24__15_02_2023.csv
max_num_imgs2test:
  senticap: -1
  flickrstyle10k: 1000


tgt_eval_results_file_name: avg_evaluation.csv
tgt_eval_results_file_name_for_all_frames: evaluation_all_frames.csv


tgt_eval_results_path: ~/experiments/stylized_zero_cap_experiments/27_2_23/avg_evaluation.csv
tgt_eval_results_path_for_all_frames: ~/experiments/stylized_zero_cap_experiments/27_2_23/evaluation_all_frames.csv
dir_path_for_eval_only_fluency: ~/experiments/stylized_zero_cap_experiments/27_2_23/fluency_statistics

factual_captions_path:
  senticap: /Users/danielabendavid/data/source/coco/factual_captions.pkl
test_set_path:
  senticap: /Users/danielabendavid/data/senticap/annotations/test.pkl
  flickrstyle10k: /Users/danielabendavid/data/flickrstyle10k/annotations/test.pkl
imgs_path:
  senticap: /Users/danielabendavid/data/senticap/images
  flickrstyle10k: /Users/danielabendavid/data/flickrstyle10k/images
txt_cls_model_paths:
  senticap: ~/checkpoints/best_models/senticap/best_senticap_text_style_classification_model.pth
  flickrstyle10k: ~/checkpoints/best_models/flickrstyle10k/best_flickrstyle10k_text_style_classification_model.pth
hidden_state_to_take_txt_cls:
  senticap: -1
  flickrstyle10k: -1

txt_embed_model_paths:
  senticap: ~/checkpoints/best_models/senticap/best_text_style_embedding_model_senticap.pth
  flickrstyle10k: ~/checkpoints/best_models/flickrstyle10k/best_text_style_embedding_model_flickrstyle10k.pth

hidden_state_to_take_txt_style_embedding:
  senticap: -2

model_based_on: 'bert'
test_imgs:
  senticap: /home/nlp/tzufar/data/senticap/images/test
  flickrstyle10k: /home/nlp/tzufar/data/flickrstyle10k/images/test
styles:
  senticap: [positive, negative]
  flickrstyle10k: [humor, romantic]

#specific_imgs_to_test: [225571, 471814, 72873, 357322, 106314, 368459, 575135, 423830, 51258, 265596, 551518, 448703]
#specific_img_idxs_to_test: [60, 61, 62, 63, 64, 65, 66, 67, 128, 129, 130, 131, 132, 133, 134, 135]
img_idx_to_start_from: 0
max_num_of_imgs: 5 #-1
specific_idxs_to_skip: [2,3]

labels_dict_idxs:
  senticap:
    positive: 0
    negative: 1
  flickrstyle10k:
    humor: 0
    romantic: 1

#emoji
use_single_emoji_style: False
idx_emoji_style_dict:
  senticap:
#    positive: 53
#    negative: 34
    positive: [0,4,6,7,8,13,15,16,17,18,23,24,36,40,53,60] # 53
    negative: [1,2,3,5,12,22,27,29,32,34,35,37,39,42,43,44,45,46,52,55,56,58] # 34
  flickrstyle10k:
    humor: #0
    romantic: #23

emoji_vocab_path: ~/projects/torchMoji/model/vocabulary.json
emoji_pretrained_path: ~/projects/torchMoji/model/pytorch_model.bin
maxlen_emoji_sentence: 30
num_classes: 64
idx_emoji_style_dict:
  senticap:
    positive: 53
    negative: 34
  flickrstyle10k:
    humor: 0
    romantic: 23
