param_int: 1
param_float: 1.
param_str: hi
param_list_of_everything: [a, 1, '1']
param_dict:
  k0: v0
  k1: v1
  nested_k:
    k00: v00
    and_so_on: more_values
batch_size: 400
inner_batch_size: 1
best_model_name: best_trained_model_flickrstyle10k.pth
model_name: trained_model_flickrstyle10k.pth
mean_vec_emb_file: flickrstyle10k_mean_class_embedding.p
median_vec_emb_file: flickrstyle10k_median_class_embedding.p
data_name: flickrstyle10k
data_file: ['humor_train.txt', 'romantic_train.txt']
experiment_name: cur_time
csv_file_name_train: 'flickrstyle10k_train.csv'
csv_file_name_test: 'flickrstyle10k_test.csv'
visual_csv_file_name_train: 'visual_flickrstyle10k_train.csv'
visual_csv_file_name_test: 'visual_flickrstyle10k_test.csv'
tgt_file_pairs_list: flickrstyle10k_pairs_list.p
num_workers: 10
plot_only_clustering: False
desired_labels: 'all' #[embarrassment, joy, anger, love, annoyance, nervousness]
undesired_label: 'neutral'
resume: False # resume running in wb
load_model: False
run_id: