

epochs: 200
lr: 1e-6
batch_size: 16
margin: 1.4
inner_batch_size: 1
best_model_name: best_text_style_embedding_model_flickrstyle10k.pth
model_name: latest_text_style_embedding_model_flickrstyle10k.pth
mean_vec_emb_file: flickrstyle10k_mean_class_embedding.p
median_vec_emb_file: flickrstyle10k_median_class_embedding.p
txt_cls_model_path: checkpoints/best_models/senticap/humor_romantic_best_text_style_classification_model.pth
data_name: [flickrstyle10k]
data_file: ['flickrstyle10k/annotations/funny_train.txt', 'flickrstyle10k/annotations/romantic_train.txt']
experiment_name: cur_time
csv_file_name_train: 'flickrstyle10k_train.csv'
csv_file_name_test: 'flickrstyle10k_test.csv'
visual_csv_file_name_train: 'visual_flickrstyle10k_train.csv'
visual_csv_file_name_test: 'visual_flickrstyle10k_test.csv'
tgt_file_pairs_list: flickrstyle10k_pairs_list.p
num_workers: 10
plot_only_clustering: False
desired_labels: 'all'
undesired_label: 'neutral'
resume: False # resume running in wb
load_model: False
run_id:
wandb_mode: online #'disabled, offline, online'
