data_name: flickrstyle10k
task: train #test
#task: test #test
load_model: False
test_on_df: [train, val, test]
global_dir_name_for_save_models: flickrstyle10k_text_style_classification


#path_for_loading_best_model: /home/nlp/tzufar/checkpoints/flickrstyle10k_text_style_classification/15_03_2023/02_35_08__15_03_2023/best_flickrstyle10k_text_style_classification_model.pth

#terminal
#best_model_name: 22_2_23_f1=0.855/best_flickrstyle10k_text_style_classification_model.pth #best_twitter_trained_model.pth #todo: good model for evaluation
best_model_name: best_flickrstyle10k_text_style_classification_model.pth #best_twitter_trained_model.pth
model_name: flickrstyle10k_text_style_classification_model.pth
wandb_mode: disabled #'disabled, offline, online'


#arithmetics_style_imgs: [49, 52, 53]
style_img:
  factual: 49
  humor: 52
  romantic: 53

labels_dict_idxs:
  humor: 0
  romantic: 1


arithmetics_weights: [1, -0.5, 0.5]
img_idx_to_start_from: 0
desired_labels: [humor, romantic] #[factual, humor, romantic]

epochs: 20
lr: 0.00001
batch_size: 16
margin: 0.04
hidden_state_to_take: -1
last_layer_idx_to_freeze: -1
freeze_after_n_epochs: 1000000000
inner_batch_size: 1

#--freeze_after_n_epochs=6 --hidden_state_to_take=-2 --last_layer_idx_to_freeze=8 --lr=1e-05 --scale_noise=0.04

txt_cls_model_path: checkpoints/best_models/flickrstyle10k/humor_romantic_best_text_style_classification_model.pth
data_file: ['flickrstyle10k/annotations/funny_train.txt', 'flickrstyle10k/annotations/romantic_train.txt']
experiment_name: cur_time
csv_file_name_train: 'flickrstyle10k_train.csv'
csv_file_name_test: 'flickrstyle10k_test.csv'
visual_csv_file_name_train: 'visual_flickrstyle10k_train.csv'
visual_csv_file_name_test: 'visual_flickrstyle10k_test.csv'
tgt_file_pairs_list: flickrstyle10k_pairs_list.p
num_workers: 10
plot_only_clustering: False
#desired_labels: 'all' #[embarrassment, joy, anger, love, annoyance, nervousness]
undesired_label: 'neutral'
resume: False # resume running in wb
run_id:


#text style embedding
cuda_idx_num: 0
labels_set_dict:
  humor: 0
  romantic: 1
labels_idx_to_str:
  0: humor
  1: romantic
