###### stylized ZeroCap: create captions - for run.py
data_name: flickrstyle10k
use_style_model: True
use_text_style_example: False
run_type: caption #caption, arithmetics, img_prompt_manipulation
#cond_text_dict:
#  humor: The humorous image of a
#  romantic: The romantic image of a
  #  factual: Image of a
cond_text_dict:
  humor: ""
  romantic: ""
  factual: ""

max_num_of_imgs: -1 #10 #-1
wandb_mode: online #'disabled, offline, online'
data_type: test
calc_evaluation: False

#atomic sweep  3 - total avg score = 0.3243:   https://wandb.ai/bdaniela/StylizedZeroCap/sweeps/z08bsrnr?workspace=user-bdaniela
clip_scale:  3.746143446 #2.965
ce_scale: 2.43956729 #2.318
text_style_scale: 3.797802783 #3.444
beam_size: 4 #3
num_iterations: 5 # 8

embedding_vectors_std:
  humor: 0.05536 #0.028914157
  romantic: 0.007185  #0.020412436

#ZeroCap params
zerocap_clip_scale: 1
zerocap_ce_scale: 0.2
zerocap_beam_size: 5
zerocap_num_iterations: 5
zerocap_text_style_scale: 0

target_seq_length: 15
write_debug_tracking_file: False

#arithmetics_style_imgs: [49, 52, 53]
style_img:
  factual: 49
  humor: 52
  romantic: 53

labels_dict_idxs:
  humor: 0
  romantic: 1


arithmetics_weights: [1, -0.5, 0.5]
img_idx_to_start_from: 0
desired_labels: [humor, romantic] #[factual, humor, romantic]

reset_context_delta: True
calc_fluency: True
debug_mac: False
imitate_text_style: False
text_to_imitate_list: ["humor"]
#specific_imgs_to_test: [108698]
################

#epochs: 25  # 12 #200
#batch_size: 16
#
#lr: 0.01 #1e-6
#margin: 0.8168 # 1.4
#hidden_state_to_take: -4
#last_layer_idx_to_freeze: 9
#freeze_after_n_epochs: 6



epochs: 7
lr: 0.00001
batch_size: 16
margin: 0.26
hidden_state_to_take: -4
last_layer_idx_to_freeze: 10
freeze_after_n_epochs: 4
inner_batch_size: 1
data_name: senticap

inner_batch_size: 1
best_model_name: checkpoints/best_models/flickrstyle10k/best_text_style_embedding_model_flickrstyle10k.pth
model_name: latest_text_style_embedding_model_senticap.pth

mean_vec_emb_file:  checkpoints/best_models/flickrstyle10k/flickrstyle10k_mean_class_embedding.p
median_vec_emb_file: checkpoints/best_models/flickrstyle10k/flickrstyle10k_median_class_embedding.p
std_vec_emb_file: senticap/senticap_std_class_embedding.p
txt_cls_model_path: checkpoints/best_models/flickrstyle10k/humor_romantic_best_text_style_classification_model.pth
data_file: ['flickrstyle10k/annotations/funny_train.txt', 'flickrstyle10k/annotations/romantic_train.txt']
experiment_name: cur_time
csv_file_name_train: 'flickrstyle10k_train.csv'
csv_file_name_test: 'flickrstyle10k_test.csv'
visual_csv_file_name_train: 'visual_flickrstyle10k_train.csv'
visual_csv_file_name_test: 'visual_flickrstyle10k_test.csv'
tgt_file_pairs_list: flickrstyle10k_pairs_list.p
num_workers: 10
plot_only_clustering: False
#desired_labels: 'all' #[embarrassment, joy, anger, love, annoyance, nervousness]
undesired_label: 'neutral'
resume: False # resume running in wb
load_model: False
run_id: 0


#text style embedding
cuda_idx_num: 0
labels_set_dict:
  humor: 0
  romantic: 1
labels_idx_to_str:
  0: humor
  1: romantic

txt_embed_model_name: best_text_style_embedding_model_senticap.pth
txt_embed_best_model_name: latest_text_style_embedding_model_senticap.pth
txt_embed_mean_vec_emb_file: senticap_mean_class_embedding.p
txt_embed_median_vec_emb_file: senticaptxt_embed__median_class_embedding.p
txt_embed_std_vec_emb_file: senticap_std_class_embedding.p