use_style_model: True
run_type: caption #caption, arithmetics, img_prompt_manipulation
#cond_text_list: ["Image of a", "The beautiful image of a", "The disturbing image of a"]
cond_text_list: [""]
max_num_of_imgs: 10 #-1
wandb_mode: online #'disabled, offline, online'
data_type: val

#clip_scale:  3.746143446 #2.965
#ce_scale: 2.43956729 #2.318
#text_style_scale: 3.797802783 #3.444
#beam_size: 4 #3
#num_iterations: 5 # 8
#
#std_embedding_vectors_positive: 0.05536 #0.028914157
#std_embedding_vectors_negative: 0.007185  #0.020412436

target_seq_length: 15

arithmetics_style_imgs: [49, 50, 51]
arithmetics_weights: [1, -0.5, 0.5]
img_idx_to_start_from: 0
desired_labels: [positive, negative] #[factual, positive, ngeative]

#specific_imgs_to_test: [478874, 104906]
#specific_imgs_to_test: [108698, 43128, 123810, 127451, 350107, 454661,
#     217517, 352936, 553867, 439472, 149376, 435260, 527102, 191047, 160531, 206618, 365642, 84410, 568883, 483375,
#     515303, 163076, 69229, 479597, 184606, 526044, 75990, 259597, 129786, 177407, 547041, 71738, 8204, 216096, 510864,
#     577169, 432421, 463678, 13168, 97240, 284509, 20207, 168243, 190705, 267321, 88162, 314495, 531499, 258112, 60409,
#     77954, 175831, 81998, 219589, 117508, 160031, 509270, 407260, 210221, 81594, 415880, 139637, 31280, 440842, 58949,
#     557127, 480643, 226220, 20038, 242611, 32400, 45105, 406591, 10104, 522427, 465591, 241668, 247543, 464894, 560358]

epochs: 12
lr: 0.01
batch_size: 16
margin: 0.8168
hidden_state_to_take: -4
last_layer_idx_to_freeze: 9
freeze_after_n_epochs: 6
inner_batch_size: 1
data_name: [senticap]
best_model_name: senticap/best_text_style_embedding_model_senticap.pth
model_name: latest_text_style_embedding_model_senticap.pth
mean_vec_emb_file: senticap/senticap_mean_class_embedding.p
median_vec_emb_file: senticap/senticap_median_class_embedding.p
std_vec_emb_file: senticap/senticap_std_class_embedding.p
data_file: #['flickrstyle10k/annotations/funny_train.txt', 'flickrstyle10k/annotations/romantic_train.txt']
experiment_name: cur_time
csv_file_name_train: 'senticap_train.csv'
csv_file_name_test: 'senticap_test.csv'
visual_csv_file_name_train: 'visual_senticap_train.csv'
visual_csv_file_name_test: 'visual_senticap_test.csv'
tgt_file_pairs_list: senticap_pairs_list.p
num_workers: 10
plot_only_clustering: True
#desired_labels: 'all' #[embarrassment, joy, anger, love, annoyance, nervousness]
undesired_label: 'neutral'
resume: False # resume running in wb
load_model: False
run_id: 0
# stylized ZeroCap
reset_context_delta: True
calc_fluency: True
debug_mac: False


## for debug
#max_num_of_imgs: 1
#target_seq_length: 1
#beam_size: 1
#num_iterations: 1