data_name: senticap
task: test #train / test / single_test
load_model: True
test_on_df: [train, val, test]
global_dir_name_for_save_models: senticap_text_style_classification_fast_search

best_model_name: best_senticap_text_style_classification_model.pth #best_twitter_trained_model.pth
model_name: senticap_text_style_classification_model.pth
wandb_mode: online #'disabled, offline, online'
#path_for_loading_best_model: /Users/danielabendavid/checkpoints/best_models/senticap/best_senticap_text_style_classification_model.pth
#path_for_loading_best_model: /home/nlp/tzufar/checkpoints/17_02_2023/14_08_45__17_02_2023/best_senticap_text_style_classification_model.pth

labels_dict_idxs:
  positive: 0
  negative: 1
desired_labels: [positive, negative] #[factual, positive, negative]

epochs: 50
lr: 0.001
batch_size: 16
margin: 0.26
hidden_state_to_take: -1
last_layer_idx_to_freeze: -1  # 9
freeze_after_n_epochs: 1000000 #10
inner_batch_size: 1
scale_noise: 0.08

txt_cls_model_path: checkpoints/best_models/senticap/pos_neg_best_text_style_classification_model.pth
experiment_name: cur_time
csv_file_name_train: 'senticap_train.csv'
csv_file_name_test: 'senticap_test.csv'
visual_csv_file_name_train: 'visual_senticap_train.csv'
visual_csv_file_name_test: 'visual_senticap_test.csv'
tgt_file_pairs_list: senticap_pairs_list.p
num_workers: 10
plot_only_clustering: False
undesired_label: 'neutral'
resume: False # resume running in wb
run_id:


#text style embedding
cuda_idx_num: 0
labels_set_dict:
  positive: 0
  negative: 1
labels_idx_to_str:
  0: positive
  1: negative
