###### stylized ZeroCap: create captions - for run.py
use_style_model: False
use_text_style_example: False
run_type: caption #caption, arithmetics, img_prompt_manipulation
cond_text_dict:
  positive: The beautiful image of a
  negative: The disturbing image of a
  #  factual: Image of a

#cond_text_list:
#  positive: ""
#  negative: ""
#  factual: ""

#cond_text_list: ["Image of a", "The beautiful image of a", "The disturbing image of a"]
#cond_text_list: [""]

max_num_of_imgs: -1 #10 #-1
wandb_mode: disabled #'disabled, offline, online'
data_type: test

#debug- tocheck:
#mild -- 531
#https://wandb:ai/bdaniela/StylizedZeroCap/sweeps/z6ytzium?workspace=user-bdaniela:
#atomic sweep  3 - total avg score = 0.3243:   https://wandb.ai/bdaniela/StylizedZeroCap/sweeps/z08bsrnr?workspace=user-bdaniela
clip_scale:  3.746143446 #2.965
ce_scale: 2.43956729 #2.318
text_style_scale: 3.797802783 #3.444
beam_size: 4 #3
num_iterations: 5 # 8

embedding_vectors_std:
  positive: 0.05536 #0.028914157
  negative: 0.007185  #0.020412436

#ZeroCap params
zerocap_clip_scale: 1
zerocap_ce_scale: 0.2
zerocap_beam_size: 5
zerocap_num_iterations: 5
zerocap_text_style_scale: 0

target_seq_length: 15
write_debug_tracking_file: False

#arithmetics_style_imgs: [49, 50, 51]
style_img:
  factual: 49
  positive: 50
  negative: 51

arithmetics_weights: [1, -0.5, 0.5]
img_idx_to_start_from: 0
desired_labels: [positive, negative] #[factual, positive, ngeative]

reset_context_delta: True
calc_fluency: True
debug_mac: False
imitate_text_style: False
text_to_imitate_list: ["positive"]


#specific_imgs_to_test: [108698, 43128, 123810, 127451, 350107, 454661,
#     217517, 352936, 553867, 439472, 149376, 435260, 527102, 191047, 160531, 206618, 365642, 84410, 568883, 483375,
#     515303, 163076, 69229, 479597, 184606, 526044, 75990, 259597, 129786, 177407, 547041, 71738, 8204, 216096, 510864,
#     577169, 432421, 463678, 13168, 97240, 284509, 20207, 168243, 190705, 267321, 88162, 314495, 531499, 258112, 60409,
#     77954, 175831, 81998, 219589, 117508, 160031, 509270, 407260, 210221, 81594, 415880, 139637, 31280, 440842, 58949,
#     557127, 480643, 226220, 20038, 242611, 32400, 45105, 406591, 10104, 522427, 465591, 241668, 247543, 464894, 560358]


epochs: 12
lr: 0.01
batch_size: 16
margin: 0.8168
hidden_state_to_take: -4
last_layer_idx_to_freeze: 9
freeze_after_n_epochs: 6
inner_batch_size: 1
data_name: senticap
best_model_name: checkpoints/senticap/best_text_style_embedding_model_senticap.pth
model_name: latest_text_style_embedding_model_senticap.pth

mean_vec_emb_file:  checkpoints/best_models/senticap/senticap_mean_class_embedding.p
median_vec_emb_file: checkpoints/best_models/senticap/senticap_median_class_embedding.p
std_vec_emb_file: senticap/senticap_std_class_embedding.p
txt_cls_model_path: checkpoints/best_models/senticap/pos_neg_best_text_style_classification_model.pth
data_file: #['flickrstyle10k/annotations/funny_train.txt', 'flickrstyle10k/annotations/romantic_train.txt']
experiment_name: cur_time
csv_file_name_train: 'senticap_train.csv'
csv_file_name_test: 'senticap_test.csv'
visual_csv_file_name_train: 'visual_senticap_train.csv'
visual_csv_file_name_test: 'visual_senticap_test.csv'
tgt_file_pairs_list: senticap_pairs_list.p
num_workers: 10
plot_only_clustering: True
#desired_labels: 'all' #[embarrassment, joy, anger, love, annoyance, nervousness]
undesired_label: 'neutral'
resume: False # resume running in wb
load_model: False
run_id: 0


#text style embedding
cuda_idx_num: 0
labels_set_dict:
  positive: 0
  negative: 1
labels_idx_to_str:
  0: positive
  1: negative
txt_embed_model_name: best_text_style_embedding_model_senticap.pth
txt_embed_best_model_name: latest_text_style_embedding_model_senticap.pth

txt_embed_mean_vec_emb_file: senticap_mean_class_embedding.p
txt_embed_median_vec_emb_file: senticaptxt_embed__median_class_embedding.p
txt_embed_std_vec_emb_file: senticap_std_class_embedding.p