program: run_3_loss_v1_romantic.py
project: StylizedZeroCap_roberta_3_loss_v1_romantic
method: bayes
metric:
  goal: maximize #minimize
  name:  evaluation/final_avg_total_score
parameters:
  ce_scale:
    max: 0.8  #4 #3 #5
    min: 0.01 #2 #1
    distribution: uniform
#  clip_scale:
#    max: 6 #6 #5
#    min: 3.6 #2.5 #1.5 #1
#    distribution: uniform
  text_style_scale:
    max: 15 #6 # 4.5 #9
    min: 0.8 #3 # 3.5 #2
    distribution: uniform

