program: run_update_vit4.py
project: StylizedZeroCap_update_vit_focus_clip
method: bayes
metric:
  goal: maximize #minimize
  name:  evaluation/final_avg_total_score
#  name:  evaluation/avg_clip_score
parameters:
  loss_scale_style_clip:
    max: 12 #4 #5
    min: 0.1 #0.5 #0.1
    distribution: uniform
  loss_scale_src_clip_clip:
    max: 5 # 5 #2.4 #3
    min: 0.1 # 0.1 #0.2 #0.1
    distribution: uniform
  ce_scale:
    max: 3 #3
    min: 0.1 #0.9 #0.1
    distribution: uniform
  clip_scale:
    max: 6 #8 #4.5 #6
    min: 1 #0.5 #0.1
    distribution: uniform
  num_iterations_clip_style:
    max: 3 #5 #6
    min: 1 #1 #3
    distribution: int_uniform
