program: run_update_vit.py
project: StylizedZeroCap_update_vit_style_embed
method: bayes
metric:
  goal: maximize #minimize
  name:  evaluation/final_avg_total_score
parameters:
  num_iterations_clip_style:
    max: 6
    min: 1
    distribution: int_uniform
  loss_scale_style_clip:
    max: 33
    min: 0.1
    distribution: uniform
  loss_scale_src_clip_clip:
    max: 3
    min: 0.1
    distribution: uniform
#  ce_scale:
#    max: 3
#    min: 0.1
#    distribution: uniform
#  clip_scale:
#    max: 3
#    min: 0.1
#    distribution: uniform
