program: run.py
project: StylizedZeroCap_erc
method: bayes
metric:
  goal: maximize #minimize
  name:  evaluation/final_avg_total_score
parameters:
  desired_improvement_loss: #0.01
    max: 0.1
    min: 0.001
    distribution: uniform
  th_clip_loss: #35
    max: 37
    min: 30
    distribution: uniform
  th_ce_loss: #12
    max: 15
    min: 9
    distribution: uniform
  th_style_loss: #35.5
    max: 37
    min: 30
    distribution: uniform
