program: run.py
project: StylizedZeroCap_roBERTa
method: bayes
metric:
  goal: maximize #minimize
  name:  evaluation/final_avg_total_score
parameters:
  ce_scale:
    max: 3 #5
    min: 2 #1
    distribution: uniform
  clip_scale:
    max: 3 #5
    min: 1.5 #1
    distribution: uniform
  text_style_scale:
    max: 4.5 #9
    min: 3.5 #2
    distribution: uniform

