program: run_3_loss_roberta_v14.py
project: StylizedZeroCap_roberta_3_loss
method: bayes
metric:
  goal: maximize #minimize
  name:  evaluation/final_avg_total_score
#  name:  evaluation/avg_clip_score
parameters:
  ce_scale:
    distribution: categorical
    values:
      - 0.1
      - 0.2
      - 0.3
      - 0.4
      - 0.5
      - 0.6
      - 0.7
      - 0.8
#    max: 12 #3 #1.8  #4 #3 #5
#    min: 0.2 #1 #1.3 #2 #1
#    distribution: uniform
  clip_scale:
    distribution: categorical
    values:
      - 11
      - 12
      - 13
      - 14
      - 15
      - 16
      - 17
      - 18
  sentiment_temperature:
    distribution: categorical
    values:
      - 0.0001
      - 0.001
      - 0.005
      - 0.01
      - 0.05
      - 0.1
      - 1

#    max: 20 #7 #6 #6 #5
#    min: 6 #4.5 #3.6 #2.5 #1.5 #1
#    distribution: uniform
#  text_style_scale:
#    distribution: categorical
#    values:
#      - 0.5
#      - 0.7
#      - 0.9
#      - 1.8
#      - 3.2
#      - 6.4
#    max: 8 #3.6 #4.7 #5 #6 # 4.5 #9
#    min: 0.5 #1 #2 #4.2 #3 # 3.5 #2
#    distribution: uniform

