program: text_style_classification_senticap.py
project: text_style_classification_senticap
method: bayes
metric:
  goal: maximize
  name: val/best_f1_score_val
parameters:
  lr:
    values:
    - 0.001
    - 0.0001
    - 0.00001
    - 0.000001
    distribution: categorical
  hidden_state_to_take:
    max: -1
    min: -4
    distribution: int_uniform
  last_layer_idx_to_freeze:
    max: 11
    min: 0
    distribution: int_uniform
  freeze_after_n_epochs:
    max: 10
    min: 0
    distribution: int_uniform
  scale_noise:
    values:
      - 0.16
      - 0.12
      - 0.08
      - 0.04
      - 0
    distribution: categorical
