program: run_update_vit6.py
project: StylizedZeroCap_update_vit_focus_clip
method: bayes
metric:
  goal: maximize #minimize
  name:  evaluation/final_avg_total_score
#  name:  evaluation/avg_clip_score
parameters:
  sentiment_temperature:
    distribution: categorical
    values:
      - 0.001
      - 0.01
      - 0.05
      - 0.1
#    max: 0.1 #3 #1.8  #4 #3 #5
#    min: 0.05 #1 #1.3 #2 #1
#    distribution: uniform
  ce_scale:
    distribution: categorical
    values:
      - 0.2
      - 0.4
      - 0.6
      - 0.8
#    max: 3 #3
#    min: 0.1 #0.9 #0.1
#    distribution: uniform
  clip_scale:
    distribution: categorical
    values:
      - 1
      - 2
      - 4
      - 8
      - 12
#    max: 6 #8 #4.5 #6
#    min: 1 #0.5 #0.1
#    distribution: uniform
  num_iterations_clip_style:
    max: 3 #5 #6
    min: 1 #1 #3
    distribution: int_uniform
