program: run.py
project: StylizedZeroCap_with_Emoji
method: bayes
metric:
  goal: maximize #minimize
  name:  evaluation/final_avg_total_score
parameters:
  ce_scale:
    max: 6 #4
    min: 1 #3  #1.6 #1
    distribution: uniform
  clip_scale:
    max: 6 #6.5 #6
    min: 1 #4.5
    distribution: uniform
  text_style_scale:
    max: 10 #5.5 #6
    min: 1 #2.5 #1.5
    distribution: uniform
#  std_embedding_vectors_positive: #0.015731973987010497#0.028914157
#    max: 0.15
#    min: 0.029
#    distribution: uniform
#  std_embedding_vectors_negative: #0.03894146313631765#0.020412436
#    max: 0.15
#    min: 0.055
#    distribution: uniform
#  num_iterations:
#    max: 9
#    min: 5
#    distribution: int_uniform
#  beam_size:
#    max: 4
#    min: 2
#    distribution: int_uniform

