program: run_3_loss_roberta.py
project: StylizedZeroCap_roberta_3_loss
method: bayes
metric:
  goal: maximize #minimize
  name:  evaluation/final_avg_total_score
parameters:
  ce_scale:
    max: 4 #3 #5
    min: 1.3 #2 #1
    distribution: uniform
  clip_scale:
    max: 4.5 #6 #5
    min: 2.5 #1.5 #1
    distribution: uniform
  text_style_scale:
    max: 6 # 4.5 #9
    min: 3 # 3.5 #2
    distribution: uniform

