program: run.py
project: StylizedZeroCap_with_Emoji_style_mul
method: bayes
metric:
  goal: maximize #minimize
  name:  evaluation/final_avg_total_score
parameters:
  ce_scale:
    max: 3
    min: 0.1
    distribution: uniform
  clip_scale:
    max: 3
    min: 0.1
    distribution: uniform
  requires_min_clip_score_val:
      positive:
        max: 0.27
        min: 0.25
        distribution: uniform
      negative:
        max: 0.27
        min: 0.25
        distribution: uniform
  requires_num_min_clip_score_val:
      positive:
        max: 30
        min: 10
        distribution: int_uniform
      negative:
        max: 30
        min: 10
        distribution: int_uniform
  requires_min_style_score:
    positive:
      max: 0.4
      min: 0.3
      distribution: uniform
    negative:
      max: 0.4
      min: 0.3
      distribution: uniform
#  text_style_scale:
#    max: 12 #5.5 #6
#    min: 1 #2.5 #1.5
#    distribution: uniform
#  std_embedding_vectors_positive: #0.015731973987010497#0.028914157
#    max: 0.15
#    min: 0.029
#    distribution: uniform
#  std_embedding_vectors_negative: #0.03894146313631765#0.020412436
#    max: 0.15
#    min: 0.055
#    distribution: uniform
#  num_iterations:
#    max: 9
#    min: 5
#    distribution: int_uniform
#  beam_size:
#    max: 4
#    min: 2
#    distribution: int_uniform

