program: run.py
project: StylizedZeroCap
method: bayes
metric:
  goal: maximize #minimize
  name:  evaluation/final_avg_total_score
parameters:
  ce_scale:
    max: 2.5
    min: 2 #1.9
    distribution: uniform
  clip_scale:
    max: 3.8 #4
    min: 1.8 #1.5
    distribution: uniform
  text_style_scale:
    max: 5.5 #6
    min: 3.4 #2
    distribution: uniform
  std_embedding_vectors_positive: #0.028914157
    max: 0.06
    min: 0.02
    distribution: uniform
  std_embedding_vectors_negative: #0.020412436
    max: 0.035
    min: 0.007
    distribution: uniform
  num_iterations:
    max: 9
    min: 5
    distribution: int_uniform
  beam_size:
    max: 4
    min: 2
    distribution: int_uniform

