program: run.py
project: StylizedZeroCap
method: bayes
metric:
  goal: maximize #minimize
  name:  evaluation/final_avg_total_score
parameters:
  ce_scale:
    max: 2.5
    min: 1.9
    distribution: uniform
  clip_scale:
    max: 4
    min: 1.5
    distribution: uniform
  text_style_scale:
    max: 6
    min: 2
    distribution: uniform
  num_iterations:
    max: 9
    min: 5
    distribution: int_uniform
  beam_size:
    max: 4
    min: 2
    distribution: int_uniform

