program: run_mul_clip_style_v1_romantic.py
project: StylizedZeroCap_mul_clip_style_v1_romantic
method: bayes
metric:
  goal: maximize #minimize
  name:  evaluation/final_avg_total_score
#  name:  evaluation/avg_clip_score
parameters:
  ce_scale:
#    distribution: categorical
#    values:
#      - 0.6
#      - 0.7
#      - 0.8
    max: 0.8 #3 #1.8  #4 #3 #5
    min: 0.1 #1 #1.3 #2 #1
    distribution: uniform
  sentiment_temperature:
#    distribution: categorical
#    values:
#      - 0.001
#      - 0.05
    max: 0.1 #7 #6 #6 #5
    min: 0.001 #4.5 #3.6 #2.5 #1.5 #1
    distribution: uniform
