program: run.py
project: StylizedZeroCap
method: bayes
metric:
  goal: maximize #minimize
  name:  evaluation/final_avg_total_score
parameters:
  ce_scale:
    max: 2
    min: 0.2
    distribution: uniform
  clip_scale:
    max: 8
    min: 0.2
    distribution: uniform
  text_style_scale:
    max: 8
    min: 0.2
    distribution: uniform
  num_iterations:
    max: 10
    min: 5
    distribution: int_uniform
  beam_size:
    max: 10
    min: 1
    distribution: int_uniform

