dataset: flickrstyle10k # flickrstyle10k, senticap
wandb_mode: online #'disabled, offline, online' #todo:
load_model: False
plot_only_clustering: False
##########
path_for_loading_best_model: /home/nlp/tzufar/checkpoints/flickrstyle10k_style_embedding/22_03_2023/10_44_59__22_03_2023/best_text_style_embedding_model_flickrstyle10k.pth

epochs: 30

model_based_on: 'bert' # 'clip' /  'bert'
desired_labels:
  senticap: [positive, negative] #[factual, positive, ngeative]
  flickrstyle10k: [humor, romantic] #[factual, humor, romantic]

global_dir_name_for_save_models:
  senticap: senticap_style_embedding
  flickrstyle10k: flickrstyle10k_style_embedding

scale_noise:
  senticap: 0
  flickrstyle10k: 0.12 #0.08

hidden_state_to_take:
  senticap: -3
  flickrstyle10k: -2 #-3


scale_noise_txt_style_embedding:
  senticap: 0
  flickrstyle10k: 0

hidden_state_to_take_txt_style_embedding:
  senticap: -3
  flickrstyle10k: -3

last_layer_idx_to_freeze:
  senticap: 2
  flickrstyle10k: 7 #2

lr:
  senticap: 0.00001
  flickrstyle10k: 0.000001 #0.000001 #0.000001

batch_size:
  senticap: 16
  flickrstyle10k: 64 #16#16

margin:
  senticap: 0.26
  flickrstyle10k: 0.24329619513571688 #0.8016699616407108

freeze_after_n_epochs:
  senticap: 4
  flickrstyle10k: 8 #5

inner_batch_size: 1 #for the case of unbalanced data
experiment_name: cur_time

csv_file_name_train:
  senticap: 'senticap_train.csv'
  flickrstyle10k: 'flickrstyle10k_train.csv'

csv_file_name_test:
  senticap: 'senticap_test.csv'
  flickrstyle10k: 'flickrstyle10k_test.csv'

visual_csv_file_name_train:
  senticap: 'visual_senticap_train.csv'
  flickrstyle10k: 'visual_flickrstyle10k_train.csv'


visual_csv_file_name_test:
  senticap: 'visual_senticap_test.csv'
  flickrstyle10k: 'visual_flickrstyle10k_test.csv'

tgt_file_pairs_list:
  senticap: senticap_pairs_list.p
  flickrstyle10k: flickrstyle10k_pairs_list.p
num_workers: 10
#desired_labels: 'all' #[embarrassment, joy, anger, love, annoyance, nervousness]
resume: False # resume running in wb
run_id:
cuda_idx_num: 0

labels_set_dict:
  senticap:
    positive: 0
    negative: 1
  flickrstyle10k:
    humor: 0
    romantic: 1

labels_idx_to_str:
  senticap:
    0: positive
    1: negative
  flickrstyle10k:
    0: humor
    1: romantic

best_model_name:
  senticap: best_text_style_embedding_model_senticap.pth
  flickrstyle10k: best_text_style_embedding_model_flickrstyle10k.pth

model_name:
  senticap: text_style_embedding_model_senticap.pth
  flickrstyle10k: text_style_embedding_model_flickrstyle10k.pth

txt_embed_model_name:
  senticap: latest_text_style_embedding_model_senticap.pth
  flickrstyle10k: latest_text_style_embedding_model_flickrstyle10k.pth
txt_embed_best_model_name:
  senticap: best_text_style_embedding_model_senticap.pth
  flickrstyle10k: best_text_style_embedding_model_flickrstyle10k.pth
txt_embed_mean_vec_emb_file:
  senticap: senticap_mean_class_embedding.p
  flickrstyle10k: flickrstyle10k_mean_class_embedding.p
txt_embed_std_vec_emb_file:
  senticap: senticap_std_class_embedding.p
  flickrstyle10k: flickrstyle10k_std_class_embedding.p
