batch_size: 50
inner_batch_size: 50
best_model_name: best_text_style_classification_model.pth #best_twitter_trained_model.pth
model_name: text_style_classification_model.pth
experiment_name: cur_time
lr: 0.000001
weight_decay: 0.01
data_file: ''
csv_file_name_train: ''
csv_file_name_test: ''
visual_csv_file_name_train: ''
visual_csv_file_name_test: ''
mean_vec_emb_file: ''
median_vec_emb_file: ''

num_workers: 10
plot_only_clustering: False
desired_labels: all
undesired_label: ''
data_name: text_style_classification
resume: False # resume running in wb
run_id: ''
load_model: False