param_int: 1
param_float: 1.
param_str: hi
param_list_of_everything: [a, 1, '1']
param_dict:
  k0: v0
  k1: v1
  nested_k:
    k00: v00
    and_so_on: more_values
batch_size: 5  # todo - move to parser/yaml and use args.<var>
inner_batch_size: 3  # todo - move to parser/yaml and use args.<var>
